modLoader = "javafml"
loaderVersion = "[41,)"
license = "GNU AGPL 3.0"
[[mods]]
modId = "enhancedarmaments"
version = "${file.jarVersion}"
displayName = "Enhancedarmaments-forge"
authors = "cnlimiter"
description = ""
[[dependencies.enhancedarmaments]]
modId = "forge"
mandatory = true
versionRange = "[41.1.0,)"
ordering = "NONE"
side = "BOTH"